sudo: required
services:
- docker
env:
  global:
    - IMAGE_NAME=daxko/netcore2-node-awscli-serverless
    - DOCKER_REGISTRY_USER:
      secure: Wo4Gkcx6JscYr4/v22bF+i5z0k6fcUtSWikGYfY3VQ7BN7S8g8W2mjknG2Jm3V01+RvjBDxgWfOP5drtMZAyhcl4jth8fYq7QjLycpjwe+s5IcBO8SCa9Rq8AzV02vwN7qlLduaG7H8p7aO+WMDHIS2i4Q7iQitIf8bzqeopR3aJtcRWbSMjv3yebEZnDZBgxdMJO3hijssv1yobO5Z9aLgWrYw+jxZWzUbiYUOqS6WAK+cqushgqh7wSBPAPI1TC5v9n+ba8OBHokbWbJ4MT+i5dc7TXnMTCH5I2nGHMebjQO5tALZhGHYB/0jwX+FC9wmsTXWxm/1fah6gjgDpcc36e+fud9z62fCIy7/ZnyGBNCTYLmn26sbe/62D2Y3DSHU9NmvhuaF/1MpzRQ6c8qqu4WLlEJtf2CxSB1IVeNDAHaW0dbHStxRzfgWs845nqnL83Q29FtaPoV5s+iOYUJ6yYkRd6Lsx5zdZoUoT2SEE71bPSdxc20tnrMJOFP8jXZZl8eA39X5m+Rs0CB5ZAa2UhgZZMZifhLgaSUkyBPfzgfgqtqkDGNTjz/8rmECjNAY3nokLy8M5+1p3lfi2n1Hg5mAWJmZEfaO0uUqpTjzCceJ1DT2dfuqHt/U/2Y4J6nlY73m3Xho7awvDSDNwLfu88yu8cE1+LGxTc0cUykc=
    - DOCKER_REGISTRY_PASSWORD:
      secure: KIU3QlXrRBhrycJxu5NOjCw42ocmkIVRE/IhkVlAXi1HMDHesmCfQQthWeiRvn8MTrQWbwRsY8jpvXSi41uXLNgLuEFojfFEn1sk1KZfQRzt/5s2MjIC4TKvQlBu/+WLtKuNFVbXHUTJNwKaJPZgrWINVH//X6ggi63dVaITZQSgWgNX1Dd+QmA9W1dweH+uYfD7fNgbiCt3BkByI2FM+quWUiRquhwWa/6goYFk31F2r18YgXRNre8eADRpUu57QGAQGzti6GBHUOSGeBSmBqdO51+GyR9mIZReKHbpk0bZAiNYnvzFXM/mQn8rCpdrwRWBNANF0OqZ/yAurtniV/IX88HH4rmv+J/FR4bACXxFl7LPx6xsNF2HKNaqFggmZU4ysrjpTd9JBdwluzITuU/FNLsvBbeD4ngCvY2ZMi1GWMyOYwWrgChcAaBPrFpMlDyUFcenNs+a+mjFHLNVtM/YD+q8l1BXPtd+xoF6xmtZa/tL+HO3rdQuTzcoRSz0JdslubL90VhQ8vXHfVVAwSdtrZJyLzWNmENIoJL2ocaOtaIpJ0b/EWDTWjmj7Ig9P8ph5uCHDBE/gPfGJfGXo+tkVJRMHcwQbg9ccmlFE7S3CSckBZGo4LaFMS9WnnlUf/SSToBNnvxWieBirRvOdaqvP7tT+ix0PRysaoShpKE=
script:
- docker build -t "$IMAGE_NAME" .
before_deploy:
- docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
