sudo: required
services:
- docker
env:
  global:
    - IMAGE_NAME=daxko/netcore2-node-awscli-serverless
script:
- docker build -t "$IMAGE_NAME" .
before_deploy:
- docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
